_target_: fz_openqa.datamodules.pipes.Sampler

field: document
proposal_score_key: proposal_score
idx_key: row_idx
log_weight_key: proposal_log_weight
update: True

config:
  total: ${datamodule.n_documents}
  temperature: 1.0
