_target_: fz_openqa.datamodules.pipes.Sampler

total: ${datamodule.n_documents}

match_score_key: match_score
proposal_score_key: proposal_score
field: document
replace: false
largest: false
temperature: 1.0
