_target_: fz_openqa.datamodules.pipes.Sampler

total: ${datamodule.n_documents}

match_score_key: match_score
retrieval_score_key: retrieval_score
field: document
replace: false
largest: false
temperature: 1.0
