name: ${base.name}
resume: False
num_samples: 5000
metric: ${base.target_metric}
mode: ${base.target_mode}
resources_per_trial:
  cpu: ${base.cpus}
  gpu: ${base.gpus}
fail_fast: False
raise_on_failed_trial: False
local_dir: ${sys.work_dir}
scheduler:
  _target_: ray.tune.schedulers.AsyncHyperBandScheduler
  max_t: 100
  grace_period: 2
search_alg:
  _target_: ray.tune.suggest.hyperopt.HyperOptSearch
  points_to_evaluate: null
