name: ${base.name}
resume: False
num_samples: 5000
metric: ${base.target_metric}
mode: ${base.target_mode}
resources_per_trial:
  cpu: ${base.cpus}
  gpu: ${base.gpus}
fail_fast: True
raise_on_failed_trial: False
#  checkpoint_freq: 0
#  checkpoint_at_end: False
local_dir: ${sys.work_dir}
  #  progress_reporter:
  #    _target_: ray.tune.CLIReporter
#    metric_columns: ['validation/loss', 'validation/F1']
scheduler:
  _target_: ray.tune.schedulers.AsyncHyperBandScheduler
  max_t: 1000
  grace_period: 5
search_alg:
  _target_: ray.tune.suggest.hyperopt.HyperOptSearch
  points_to_evaluate: null
