defaults:
  - scheduler: null
  - search_alg: null

name: ${base.name}
resume: False
num_samples: 1
metric: ${base.target_metric}
mode: ${base.target_mode}
resources_per_trial:
  cpu: ${base.cpus}
  gpu: ${base.gpus}
fail_fast: False
raise_on_failed_trial: False
local_dir: ${sys.work_dir}
