[tool.poetry]
name = "nlp-lightning"
version = "0.0.1"
description = "A template for NLP project with Pytorch Lightning, Hydra and Transformers"
authors = ["Valentin Liévin <valentin.lievin@gmail.com>"]
packages = [
    { include = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.8.1"
rich = "^10.2.2"
wandb = "^0.10.30"
pytorch-lightning = "^1.3.2"
transformers = "^4.6.0"
tokenizers = "^0.10.2"
hydra-core = {version="^1.0", allow-prereleases = true}
datasets = "^1.6.2"
hydra-colorlog = {version="^1.0.1", allow-prereleases = true}

[tool.poetry.scripts]
nlp-lightning = "src.cli:main"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
