[tool.poetry]
name = "fz-openqa"
version = "0.0.1"
description = "Medical Open Domain Quetion Answering"
authors = ["Valentin Liévin <valentin.lievin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.8.1"
rich = "^10.2.2"
wandb = "^0.10.30"
pytorch-lightning = { git = "https://github.com/PyTorchLightning/pytorch-lightning.git", tag = "1.3.8" }
torchmetrics = {git= "https://github.com/PyTorchLightning/metrics.git", tag="v0.4.1rc0"}
transformers = "^4.6.0"
tokenizers = "^0.10.2"
datasets = "^1.6.2"
hydra-core = {version="^1.1", allow-prereleases = true}
hydra-colorlog = {version="^1.0.1", allow-prereleases = true}
faiss-cpu = { version = "^1.7.1", allow-prereleases = true }
gdown = "^3.13.0"
elasticsearch = "^7.13.2"

[tool.poetry.scripts]
fzqa = "fz_openqa.cli:main"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | \sandbox*.py
)/
'''
