[tool.poetry]
name = "fz-openqa"
version = "0.0.1"
description = "Medical Open Domain Quetion Answering"
authors = ["Valentin Liévin <valentin.lievin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
torch = "^1.10"
rich = "^10.2.2"
wandb = "^0.10.30"
pytorch-lightning = { version = "^1.5", allow-prereleases = true }
torchmetrics = { version = "^0.5", allow-prereleases = true }
transformers = "^4.6.0"
tokenizers = "^0.10.2"
datasets = "^1.4"
hydra-core = { version = "^1.1", allow-prereleases = false }
hydra-colorlog = { version = "^1.0.1", allow-prereleases = false }
faiss-cpu = { version = "=1.6.5", allow-prereleases = false }
gdown = "^3.13.0"
elasticsearch = "^7.13.2"
ray = { extras = ["default", "tune"], version = "^1.7.0", allow-prereleases = false }
hyperopt = "^0.2.5"
spacy = { version = "^3.0", allow-prereleases = true }
scispacy = { version = "^0.4.0", allow-prereleases = true }
en_core_sci_sm = { url = "https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_sm-0.4.0.tar.gz" }
en_core_sci_lg = { url = "https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_lg-0.4.0.tar.gz" }
pre-commit = "^2.15.0"
nltk = "^3.6.5"
coverage = "^6.0.2"
dill = { git = "https://github.com/emfdavid/dill.git" }
parameterized = "^0.8.1"
hypothesis = "^6.24.2"


[tool.poetry.scripts]
fzqa = "fz_openqa.cli:main"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | \sandbox*.py
  | \.github
)/
'''
