# @package _global_

# kill all idle processes using:
# > ps aux | grep ray:: | grep -v grep | awk '{print $2}' | xargs kill -9

# delete checkpoints
# > find . -type d -path "./*" -mmin +100 -exec rm -rf {} \;

defaults:
  - override /sys: hpo-titan.yaml
  - override /space: search_preprocessing.yaml
  - override /runner: hyperopt_asha.yaml

base:
  name: search_retriever
  target_metric: validation/retriever/top10_Accuracy
  target_mode: max
  # resources
  gpus: 4
  cpus: 16

ray:
  local_mode: False
  configure_logging: False

experiment:
  experiment: retriever_only.yaml
  sys: titan.yaml
  sys.cache_dir: ${sys.cache_dir}
  base.target_metric: ${base.target_metric}
  base.target_mode: ${base.target_mode}
  base.seed: null
  print_config: False
  verbose: False
  # ignore_warnings: True
  # trainer.progress_bar_refresh_rate: 0
  trainer.checkpoint_callback: True
  logger.wandb.group: ${base.name}
  callbacks: tune.yaml
  datamodule.num_workers: ${base.cpus}
  datamodule.num_proc: 1 # todo
  datamodule.use_subset: False
  trainer.max_epochs: 300
  trainer.gpus: ${base.gpus}
  trainer.strategy: dp


runner:
  fail_fast: True
  raise_on_failed_trial: True
  search_alg: null
