# @package _global_

# kill all idle processes using:
# > ps aux | grep ray:: | grep -v grep | awk '{print $2}' | xargs kill -9

defaults:
  - override /sys: hpo-titan.yaml
  - override /space: search_1.yaml
  - override /runner: default.yaml

name: search_retriever
target_metric: validation/Accuracy
target_mode: max

# resources
gpus: 4
cpus: 16

ray:
  local_mode: False
  configure_logging: False

experiment:
  experiment: retriever_only.yaml
  corpus: none.yaml
  sys: titan.yaml
  cache_dir: ${cache_dir}
  target_metric: ${target_metric}
  target_mode: ${target_mode}
  seed: null
  print_config: False
  verbose: False
  ignore_warnings: True
  trainer.progress_bar_refresh_rate: 0
  trainer.checkpoint_callback: True
  logger.wandb.group: ${name}
  callbacks: tune.yaml
  datamodule.train_batch_size: 24
  datamodule.eval_batch_size: 512
  datamodule.num_workers: ${cpus}
  trainer.max_epochs: 100
  trainer.gpus: ${gpus}
  trainer.accelerator: dp
