model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: ${base.target_metric} # name of the logged metric which determines when model is improving
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True # additionally always save model from last epoch
  mode: ${base.target_mode} # can be "max" or "min"
  verbose: False
  dirpath: "${getcwd:}/checkpoints/"
  filename: ${base.ckpt_filename}
