progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar
  theme:
    _target_: pytorch_lightning.callbacks.progress.rich_progress.RichProgressBarTheme
    description:  "white"
    progress_bar: "#80ffdb"
    progress_bar_finished:  "#5390d9"
    progress_bar_pulse:  "#6930c3"
    batch_progress: "white"
    time:  "grey54"
    processing_speed: "#80ffdb"
    metrics:  "white"
