defaults:
  - index: elasticsearch

# text formatter
text_formatter: ${datamodule.text_formatter}

# passage config
max_length: null
passage_length: 200
passage_stride: 100
add_encoding_tokens: ${datamodule.add_encoding_tokens}
append_document_title: False

# meta
cache_dir: ${cache_dir} # cache_dir is specified in config.yaml
num_workers: ${datamodule.num_workers}
pin_memory: ${datamodule.pin_memory}
persistent_workers: ${datamodule.persistent_workers}
num_proc:  ${datamodule.num_proc}
verbose: ${verbose}

# base
use_subset: False
train_batch_size: ${datamodule.train_batch_size}
eval_batch_size: ${datamodule.eval_batch_size}
