_target_: fz_openqa.datamodules.corpus_dm.FzCorpusDataModule

input_dir: null
cache_dir: ${cache_dir} # cache_dir is specified in config.yaml
add_encoding_tokens: ${datamodule.add_encoding_tokens}
append_document_title: ${datamodule.append_document_title}
train_batch_size: ${datamodule.train_batch_size}
eval_batch_size: ${datamodule.eval_batch_size}
num_workers: ${datamodule.num_workers}
pin_memory: ${datamodule.pin_memory}
persistent_workers: ${datamodule.persistent_workers}
max_length: null
num_proc: 4
use_subset: False
passage_length: 200
passage_stride: 100
verbose: ${verbose}

index_type: bm_25
