_target_: fz_openqa.datamodules.fz_x_medqa_dm.FZxMedQADataModule

cache_dir: ${sys.cache_dir} # cache_dir is specified in config.yaml
is_gold: True
train_batch_size: 64
eval_batch_size: 128
num_workers: 4
pin_memory: False
persistent_workers: False
max_length: 512
use_subset: False
num_proc: 1
verbose: ${verbose}