defaults:
  - sampler/none@train_sampler
  - sampler/none@eval_sampler

_target_: fz_openqa.datamodules.new_dm.NewDm
add_encoding_tokens: True
append_document_title: True
cache_dir: ${cache_dir} # cache_dir is specified in config.yaml
train_batch_size: 64
eval_batch_size: 128
num_workers: 4
pin_memory: True
persistent_workers: False
max_length: 512
use_subset: False
num_proc: 1
verbose: ${verbose}
filter_gold: True

special_argument: "value"
