defaults:
  - builder: openqa
  - text_formatter: none
  - tokenizer: pretrained
  - reader_tokenizer: pretrained
  - index_builder: elasticsearch
  - preprocessing_op: none
  - sampler: priority
  - transform: none
  - dataset_update: no_update

_target_: fz_openqa.datamodules.DataModule

# datamodule args
train_batch_size: 10
eval_batch_size: 20
num_workers: 4
pin_memory: True
persistent_workers: False
drop_last: False

# global: dataset preprocessing
add_qad_tokens: false
add_special_tokens: true
subset_size: null
corpus_subset_size: null
num_proc: 4
cache_dir: ${sys.shared_cache_dir}


# global: openqa
n_retrieved_documents: 100
n_max_retrieved_documents: 1000
n_documents:
  train: 10
  validation: 100
  test: 100
