defaults:
  - builder: openqa
  - text_formatter: simple_lowercase
  - tokenizer: pretrained
  - index_builder: elasticsearch
  - relevance_classifier: exact_match
  - dataset_filter: none
  - sampler: random
  - transform: none

_target_: fz_openqa.datamodules.DataModule

# datamodule args
train_batch_size: 10
eval_batch_size: 20
num_workers: 4
pin_memory: True
persistent_workers: False
drop_last: False

# global: dataset preprocessing
add_encoding_tokens: true
add_special_tokens: true
use_subset: false
num_proc: 4
cache_dir: ${sys.cache_dir}


# global: openqa
n_retrieved_documents: 1000
n_documents:
  train: 10
  validation: 100
  test: 100
