_target_: src.datamodules.fz_x_medqa_dm.FZxMedQA

data_dir: ${data_dir} # data_dir is specified in config.yaml
is_gold: True
train_batch_size: 64
eval_batch_size: 128
num_workers: 2
pin_memory: False
max_length: 512
use_subset: False
update_cache: True