QUERY_TOKEN = "<|QUERY|>"
QUERY_MASK = "<|QMASK|>"
DOC_TOKEN = "<|DOC|>"
ANS_TOKEN = "<|ANS|>"
TRUNCATED_TOKEN = "<|TRUNCATED|>"

ADDITIONAL_SPECIAL_TOKENS = [QUERY_TOKEN, DOC_TOKEN, ANS_TOKEN, QUERY_MASK, TRUNCATED_TOKEN]
