_target_: ???

max_length: null
subset_size: ${datamodule.subset_size}

# global
tokenizer: ${datamodule.tokenizer}
cache_dir: ${sys.cache_dir}
num_proc: ${datamodule.num_proc}
text_formatter: ${datamodule.text_formatter}
add_qad_tokens: ${datamodule.add_qad_tokens}
add_special_tokens: ${datamodule.add_special_tokens}
