# @package _global_

defaults:
  - override /model/head: colbert # todo colbert
  - override /datamodule/index_builder: colbert # todo colbert


# OpenQA builder parameters
builder:
  dataset_builder:
    query_expansion: 350

# Index parameters
index_builder:
  faiss_args:
    factory: IVF100,PQ16x8
