# @package _global_

defaults:
  - override /model/bert: mini
  - override /model/module/retriever_head: colbert
  - override /model/module/reader_head: colbert
  - override /model/module/gradients: in_batch
  - override /datamodule/index_builder: ${model/module/retriever_head}


trainer:
  gpus: 1
  accumulate_grad_batches: 4

datamodule:
  train_batch_size: 8
  eval_batch_size: 8
  num_workers: 4
  dataset_update:
    freq: 10

  # dataset
  builder:
    dataset_builder:
      use_subset: True
    corpus_builder:
      use_subset: True

  # index
  index_builder:
    faiss_args:
      factory: Flat



logger:
  wandb:
    group:
      option-retriever-debug
