# @package _global_

defaults:
  - override /model/bert: mini
  - override model/module/head: dpr
  - override /datamodule/index_builder: ${model/model/head}


trainer:
  gpus: 1
  accumulate_grad_batches: 4

## activate dynamic resampling in the model
model:
  head:
    output_size: 128
    max_batch_size: 300
    normalize: false
  module:
    grad_expr: reinforce

datamodule:
  train_batch_size: 8
  eval_batch_size: 8
  num_workers: 4
  # dataset re-indexing
  dataset_update: null
#    # freq: 5 # todo [:E] --reverted [:F
#    reset_optimizer: false
#    index_first_epoch: false
#    builder_args:
#      relevance_classifier: null


  # dataset
  builder:
    dataset_builder:
      use_subset: True
    corpus_builder:
      use_subset: True

  # index
  index_builder:
    faiss_args:
      factory: Flat



logger:
  wandb:
    group:
      option-retriever-debug
