# @package _global_

defaults:
  - override /model/module/retriever_head: dpr

model:
  module:
    retriever_head:
      output_size: 768
      normalize: false

datamodule:
  # index
  index_builder:
    index_factory: Flat
