# @package _global_

defaults:
  - override /model/module/retriever_head: dpr

model:
  metric_size: 768
  module:
    retriever_head:
      output_size: null
      use_soft_score: false
      compute_agg_score: false
      normalize: true
      scale_init: 1
      target_scale_init: 1
      learn_scale: false
      auto_scale: false
