# @package _global_

defaults:
  - override /model/head: dense
  - override /datamodule/index_builder: ${model/head}

## activate dynamic resampling in the model
model:
  head:
    output_size: 768 # next exp
    max_batch_size: 300
    normalize: false

datamodule:

  # index
  index_builder:
    faiss_args:
      factory: Flat
