# @package _global_

# path/url to the checkpoint (by default this loads the previous configuration,
#  not the trainable model, unless `restore_from_checkpoint` is set to True)
checkpoint: https://drive.google.com/file/d/1y3nQz9nbqnwwZxEeWP1IQljM5J7u0zJz/view?usp=sharing
# the config keys listed here will be overridden with the ones from the checkpoint
config_overrides:
  - datamodule.index_builder
# the datamodule will be built using the following model as argument
setup_with_model: ${checkpoint}
