# @package _global_

defaults:
  - override /model/bert: roberta-base #deberta-v3-base
  - override /datamodule/relevance_classifier: none

setup_with_model: true

# override the builder parameters to use the quality builder
datamodule:
  # documents
  n_retrieved_documents: 300
  builder:
    # QuALITY questions are the same for each option, therefore the nesting level is 1.
    document_nesting_level: 1

    # update the builer parameters to use the quality builder
    dataset_builder:
      dset_name: quality
      query_expansion: 32
      n_query_tokens: 1
    corpus_builder:
      _target_: fz_openqa.datamodules.builders.QuALITYCorpusBuilder
      passage_length: 200
      passage_stride: 100

    # Index parameters
    index_builder:
      p: 100
      dtype: float16
      max_chunksize: null
      maxsim_chunksize: 4_000
      persist_cache: false
      index_factory: Flat
      handler: multi
      nprobe: 1
      keep_faiss_on_cpu: false
      train_faiss_on_cpu: true


logger:
  wandb:
    group: option-retriever-quality
