# @package _global_

defaults:
  - override /model/bert: roberta-base #deberta-v3-base
  - override /datamodule/relevance_classifier: none

base:
  device_batch_size: 2
  infer_batch_mul: 100

trainer:
  val_check_interval: 1.0

model:
  hidden_size: 128

# override the builder parameters to use the quality builder
datamodule:
  dset_name: race
  corpus_name: race
  # documents
  n_retrieved_documents: 500

  # dataset updates
  dataset_update:
    freq: 10_000
    reset_optimizer: true
    test_every_update: false
    builder_args:
      relevance_classifier: null

  builder:
    # update the builder parameters to use the quality builder
    dataset_builder:
      max_length: 128
      query_expansion: 128

    # Index parameters
    index_builder:
      engines:
        es:
          config:
            filter_with_doc_ids: true


logger:
  wandb:
    group: option-retriever-quality
