# @package _global_

defaults:
  - override /model/bert: roberta-base #deberta-v3-base
  - override /model/head: dense
  - override /datamodule/index_builder: static
  - override /datamodule/relevance_classifier: none
  - override /datamodule/sampler: none

trainer:
  gpus: 8
  accumulate_grad_batches: 4
  val_check_interval: 0.5

## activate dynamic resampling in the model
model:
  module:
    resample_k: 10
    max_batch_size: 1000
    output_size: 128
  bert:
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1


# override the builder parameters to use the quality builder
datamodule:
  # dataloaders
  num_workers: 8
  train_batch_size: 8
  eval_batch_size: 32

  # dataset update (none, done dynamically within the model)
  dataset_update: null

  # documents
  n_retrieved_documents: 196
  builder:
    # QuALITY questions are the same for each option, therefore the nesting level is 1.
    document_nesting_level: 1

    # update the builer parameters to use the quality builder
    dataset_builder:
      dset_name: quality
      question_length: 120
      n_query_tokens: 1
    corpus_builder:
      _target_: fz_openqa.datamodules.builders.QuALITYCorpusBuilder
      passage_length: 200
      passage_stride: 150


logger:
  wandb:
    group: option-retriever-quality
