# @package _global_

defaults:
  - override /model/backbone: deberta_v3

trainer:
  val_check_interval: 0.25

base:
  device_batch_size: 1

model:
  period: 10_000

# override the builder parameters to use the quality builder
datamodule:
  dset_name: race
  corpus_name: race
  dset_max_length: 160
  n_retrieved_documents: 100
  n_documents: 8

  builder:
    index_builder:
      engines:
        es:
          config:
            filter_with_doc_ids: true
