# @package _global_

defaults:
  - override /model/bert: link

trainer:
  val_check_interval: 0.3

base:
  device_batch_size: 1

model:
  period: 10_000

# override the builder parameters to use the quality builder
datamodule:
  dset_name: race
  corpus_name: race
  dset_max_length: 160
  n_retrieved_documents: 100
  n_documents: 8

  builder:
    index_builder:
      engines:
        es:
          config:
            filter_with_doc_ids: true


logger:
  wandb:
    group: option-retriever-race
