# @package _global_

defaults:
  - override /model/bert: roberta-base #deberta-v3-base
  - override /datamodule/relevance_classifier: none
  - override /datamodule/score_transform: none

base:
  device_batch_size: 2
  infer_batch_mul: 300

trainer:
  val_check_interval: 0.5

model:
  num_warmup_steps: 20_000
  metric_size: 128
  num_lr_warmup_steps: 1_000
  module:
    split_bert_layers: 0

  optimizer_params:
    lr: 1e-5

# override the builder parameters to use the quality builder
datamodule:
  dset_name: race
  corpus_name: race
  n_retrieved_documents: 10
  n_documents: 4

  # dataset updates
  dataset_update:
    freq: ${model.num_warmup_steps}

  builder:
    # update the builder parameters to use the quality builder
    dataset_builder:
      max_length: 64
      query_expansion: 64

    # Index parameters
    index_builder:
      engines:
        es:
          config:
            filter_with_doc_ids: true


logger:
  wandb:
    group: option-retriever-race
