_target_: fz_openqa.modeling.modules.OptionRetriever

defaults:
  - reader_head: colbert
  - retriever_head: colbert
  - gradients: reinforce

resample_k: null
max_batch_size: null
_id: option_retriever
