_target_: fz_openqa.modeling.modules.ReaderRetriever

defaults:
  - gradients: renyi

_id: reader_retriever
reader_fields: lm
retriever_fields: [question, document]
skip_retriever: false
skip_reader: false
reader_tokenizer: ${datamodule.reader_tokenizer}
