_target_: fz_openqa.datamodules.pipes.OptionDropout

target_key: answer.target
keys:
  - question.input_ids
  - question.attention_mask
  - document.input_ids
  - document.attention_mask
  - documents.retrieval_score
  - document.retrieval_rank
  - document.row_idx
update: true
