# @package _global_

defaults:
  # - override /callbacks: none.yaml
  - override /sys: valv.yaml


trainer:
  gpus: 8
  accelerator: dp
  checkpoint_callback: False

datamodule:
  use_subset: False
  train_batch_size: 48
  eval_batch_size: 1024
  num_proc: 1
  num_workers: 16

corpus:
  eval_batch_size: 6000

# logger: null
