# @package _global_

defaults:
  # - override /callbacks: none.yaml
  - override /sys: valv.yaml


trainer:
  gpus: 2
  accelerator: dp
  checkpoint_callback: False

datamodule:
  use_subset: True
  train_batch_size: 6
  eval_batch_size: 32
  num_proc: 1
  num_workers: 4

logger: null
