# @package _global_

defaults:
  # - override /callbacks: none.yaml
  - override /sys: valv.yaml


trainer:
  gpus: 8
  accelerator: dp
  checkpoint_callback: Fall

datamodule:
  use_subset: False
  train_batch_size: 24 # use 48 for retriever_only
  eval_batch_size: 512 # use 1024 for retriever_only
  num_proc: 1
  num_workers: 16

corpus:
  eval_batch_size: 6000

# logger: null
