# @package _global_


defaults:
  - override /sys: local.yaml

trainer:
  gpus: 0
  checkpoint_callback: False

datamodule:
  use_subset: True
  window_size: 200
  window_stride: 100
  train_batch_size: 10
  eval_batch_size: 20
  num_proc: 1
  num_workers: 0

logger: null
callbacks: null
