# @package _global_

defaults:
  - override /sys: local.yaml
  - override /model/bert: mini.yaml

trainer:
  gpus: 0
  checkpoint_callback: False


datamodule:
  use_subset: True
  train_batch_size: 10
  eval_batch_size: 20
  num_proc: 2
  num_workers: 2

datamodule.corpus_builder:
  passage_length: 100
  passage_stride: 100

model:
  hidden_size: null

logger: null
callbacks: null
