# @package _global_


defaults:
  - override /sys: local.yaml
  # - override /callbacks: index_corpus.yaml

trainer:
  gpus: 0
  limit_train_batches: 1
  limit_val_batches: 1
  limit_test_batches: 1
  checkpoint_callback: False

datamodule:
  use_subset: True
  train_batch_size: 5
  eval_batch_size: 5
  num_proc: 1
  num_workers: 0

logger: null
