# @package _global_

defaults:
  - override /sys: local.yaml
  - override /model/bert: mini.yaml


datamodule:
  num_proc: 2
  num_workers: 2
  builder:
      dataset_builder:
        max_length: 150
      corpus_builder:
        passage_length: 100
        passage_stride: 100
