# @package _global_

defaults:
  - sys: hpo-titan.yaml
  - space: search_1.yaml
  - runner: default.yaml


# base arguments
base:
  name: null
  target_metric: validation/Accuracy
  target_mode: max
  print_config: True
  server_address: null
  # resources
  gpus: 4
  cpus: 16

ray:
  local_mode: False
  configure_logging: False
