# @package _global_

defaults:
  - sys: local
  - trainer: minimal
  - callbacks: progress_bar
  - logger: none
  - datamodule/index_builder: elasticsearch


  # hydra stuff
  - hydra: default
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

datamodule:
  num_proc: 4
  output_columns: null
  builder:
    dataset_builder:
      _target_: fz_openqa.datamodules.builders.FzQueriesBuilder
      use_subset: false

    corpus_builder:
      _target_: fz_openqa.datamodules.builders.FzCorpusBuilder
      use_subset: false
      # passage_length: 200
      # passage_stride: 100

  index_builder:
    map_kwargs:
      num_proc: ${datamodule.num_proc}
      batch_size": 100
    loader_kwargs:
      num_workers: 16
      batch_size: 4000
    persist_cache: true
    cache_dir: ${sys.cache_dir}
    shared_cache_dir: ${sys.shared_cache_dir}
    verbose: true
    progress_bar: true
    dtype: float32
    p: 100
    keep_maxsim_on_cpu: true

# command applied before overriding another config
override_ops:
  delete:
    - callbacks
    - hydra
    - logger
