# @package _global_

defaults:
  - sys: local
    # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog


version: 11
lr: 1e-4
reader_lr: ${lr}
retriever_lr: ${lr}
seed: null
wandb: true
device: cpu
num_epochs: 6
batch_size: 64
n_samples: 10
gamma: 1.
sampler: priority
temperature: 100.
max_baseline_samples: 3
hidden_size: 64
share_backbone: false
estimator: reinforce_a
use_baseline: false
noise_level: 0.95
labels: [1, 7, 5, 9]
