defaults:
  - dpr

_target_: fz_openqa.datamodules.index.ColbertOrEsIndexBuilder

faiss_args:
  factory: IVF100,PQ16x8
  metric_type: 0 # faiss.METRIC_INNER_PRODUCT

faiss_train_size: 1_000_000
p: 100
max_chunksize: 100
maxsim_chunksize: 10_000
keep_maxsim_on_cpu: true
_id: colbert
