defaults:
  - dpr

_target_: fz_openqa.datamodules.index.ColbertOrEsIndexBuilder

index_factory: IVF100,PQ16x8
faiss_train_size: 1_000_000
p: 100
max_chunksize: 100
maxsim_chunksize: 10_000
_id: colbert
