defaults:
  - elasticsearch

_target_: fz_openqa.datamodules.index.FaissOrEsIndexBuilder

index_factory: IVF100,PQ16x8
handler: flat
nprobe: 32

loader_kwargs:
  batch_size: 1000
  num_workers: 8
  pin_memory: true

faiss_train_size: 10000
in_memory: true
dtype: float32
model_output_keys: [_hq_, _hd_]
persist_cache: false
cache_dir: ${sys.cache_dir}
progress_bar: true
_id: dpr
