defaults:
  - es

# define the engines
engines:
  es:
    k: ${datamodule.n_max_retrieved_documents}
    max_batch_size: 100
    verbose: false
    merge_previous_results: true
    merge_max_size: null
    config:
      es_temperature: 10.
      auxiliary_weight: 0
      filter_with_doc_ids: false
  faiss:
    k: ${datamodule.n_max_retrieved_documents}
    max_batch_size: 512
    verbose: false
    merge_previous_results: true
    merge_max_size: ${datamodule.n_retrieved_documents}
    config:
      index_factory: "shard:IVF1000,Flat"
      train_size: 1_000_000
      max_add_per_gpu: 10_000 # todo: increase this
      add_batch_size: 1_000 # todo: increase this
      metric_type: ${model.metric_type}
      nprobe: 32
  topk:
    k: ${datamodule.n_retrieved_documents}
    max_batch_size: 10
    verbose: false
    merge_previous_results: false
    merge_max_size: null
    config: { }

# logging
id: dpr
