defaults:
  - base

_target_: fz_openqa.datamodules.index.ElasticSearchIndexBuilder

# key to index
required_keys: text

# text cleaning
filter_mode: null
text_formatter: null

# return the ES analyzed tokens
analyze_es_tokens: false

# arguments for preprocessing the index
map_kwargs:
  batch_size: 100
  num_proc: ${datamodule.num_proc}

# id for logging
id: elastic_search
