_target_: fz_openqa.datamodules.index.ElasticSearchIndexBuilder

index_key: "document.row_idx"
text_key: "document.text"
query_key: "question.text"
num_proc: ${datamodule.num_proc}
filter_mode: null
_id: elastic_search
