defaults:
  - base
  - text_filter: null
  - /datamodule/text_formatter/aggressive@text_formatter

_target_: fz_openqa.datamodules.index.ElasticSearchIndexBuilder

# text cleaning
filter_mode: null

# return the ES analyzed tokens
analyze_es_tokens: false

# arguments for preprocessing the index
prep_map_kwargs:
  batch_size: 100
  num_proc: ${datamodule.num_proc}

# id for logging
id: elastic_search
