_target_: transformers.AutoModelForMultipleChoice.from_pretrained
pretrained_model_name_or_path: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext
config:
  _target_: transformers.AutoConfig.from_pretrained
  pretrained_model_name_or_path: ${model.bert.pretrained_model_name_or_path}
  cache_dir: ${sys.shared_cache_dir}
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
