model.bert.pretrained_model_name_or_path:
  _target_: ray.tune.choice
  categories:
    - 'bert-base-cased'
    - 'dmis-lab/biobert-base-cased-v1.1'
    - 'dmis-lab/biobert-base-cased-v1.2'
    - 'allenai/biomed_roberta_base'
model.hidden_size:
  _target_: ray.tune.choice
  categories:
    - 8
    - 32
    - 64
    - 128
    - 256
model.lr:
  _target_: ray.tune.choice
  categories:
    - 1e-5
    - 3e-5
    - 6e-5
    - 1e-4
model.weight_decay:
  _target_: ray.tune.choice
  categories:
    - 0
    - 1e-5
    - 1e-4
    - 1e-3
