model.bert.pretrained_model_name_or_path:
  _target_: ray.tune.choice
  categories:
    - 'dmis-lab/biobert-base-cased-v1.1'
model.metric_siz:
  _target_: ray.tune.choice
  categories:
    - 8
    - 32
    - 64
    - 128
model.lr:
  _target_: ray.tune.choice
  categories:
    - 1e-5
model.weight_decay:
  _target_: ray.tune.choice
  categories:
    - 0
    - 1e-5
    - 1e-4
    - 1e-3
model.bert.attention_probs_dropout_prob:
  _target_: ray.tune.choice
  categories:
    - 0
    - 0.1
    - 0.3
    - 0.5
model.bert.config.hidden_dropout_prob:
  _target_: ray.tune.choice
  categories:
    - 0
    - 0.1
    - 0.3
base.seed:
  _target_: ray.tune.randint
  lower: 1
  upper: 20
datamodule.train_sampler.n_neg:
  _target_: ray.tune.randint
  lower: 0
  upper: 4
datamodule.add_qad_tokens:
  _target_: ray.tune.choice
  categories:
    - False
    - True
