datamodule.relevance_classifier._target_:
  _target_: ray.tune.grid_search
  values:
    #- fz_openqa.datamodules.pipes.ExactMatch
    #- fz_openqa.datamodules.pipes.ScispaCyMatch
    - fz_openqa.datamodules.pipes.MetaMapMatch

datamodule.builder.corpus_builder._target_:
  _target_: ray.tune.grid_search
  values:
    - fz_openqa.datamodules.builders.MedQaCorpusBuilder
    - fz_openqa.datamodules.builders.FzCorpusBuilder
    - fz_openqa.datamodules.builders.FZxMedQaCorpusBuilder
