model/bert:
  _target_: ray.tune.choice
  categories:
    - bio_bert.yaml
    - pubmed.yaml

model/head:
  _target_: ray.tune.choice
  categories:
    - cls.yaml
    - colbert.yaml

datamodule.transform.rate:
  _target_: ray.tune.choice
  categories:
    - 0
    - 0.1
    - 0.2
    - 0.3
    - 0.5
