defaults:
  - module: ???
  - optimizer: adamw
  - lr_scheduler: linear
  - backbone: mini

_target_: fz_openqa.modeling.Model

bert_id: ${model.backbone.pretrained_model_name_or_path}
tokenizer: ${datamodule.tokenizer}
cache_dir: ${sys.shared_cache_dir}
bert_lr: 1e-5
lr: 1e-3
weight_decay: 0.01
monitor_metric: ${base.target_metric}
num_training_steps: 10000
num_warmup_steps: 1000
