defaults:
  - evaluator: null
  - bert: bio_bert.yaml
  - multiple_choice_qa_reader@reader
  - qa_retriever@retriever

_target_: fz_openqa.modeling.models.multiple_choice_qa.MultipleChoiceQA

# global model parameters
bert_id: ${model.bert.pretrained_model_name_or_path}
lr: 1e-5
hidden_size: 256
weight_decay: 1e-4
dropout: 0
eval_using_corpus: True
eval_top_k: 100

reader:
  lr: ${model.lr}
  hidden_size: ${model.hidden_size}
  weight_decay: ${model.weight_decay}
  dropout: ${model.dropout}

retriever:
  lr: ${model.lr}
  hidden_size: ${model.hidden_size}
  weight_decay: ${model.weight_decay}
  dropout: ${model.dropout}
