defaults:
  - evaluator: ir_gold_supervised.yaml

_target_: fz_openqa.modeling.models.qa_retriever.QaRetriever

hidden_size: 32
bert_id: ${pretrained_model}
cache_dir: ${cache_dir}
lr: 2e-5
weight_decay: 0
dropout: 0