defaults:
  - evaluator: ir_gold_supervised.yaml
  - bert: bio_bert.yaml

_target_: fz_openqa.modeling.models.qa_retriever.QaRetriever

hidden_size: 32
cache_dir: ${cache_dir}
lr: 2e-5
weight_decay: 0
dropout: 0