name: flake8 Lint

on: [ push, pull_request ]

jobs:

  flake8-lint:
    runs-on: ubuntu-18.04
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - name: local-fix
        run: |
          # Hack to get setup-python to work on act
          # (see https://github.com/nektos/act/issues/251)
          if [ ! -f "/etc/lsb-release" ] ; then
          echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          ignore: "W503,F401,E203,E402"
          # exclude: "filename"
          max-line-length: "100"
          path: "fz_openqa/"
